#!/usr/bin/env python
"""Run axelrod
Usage:
    omni4d [-l LOGGING] [-v VERBOSITY] create [-d DBNAME] [-s SERVER] [-n PORT] [-u USER] [-p PASSWORD]
    omni4d [-l LOGGING] [-v VERBOSITY] import -f URL [-d DBNAME] [-s SERVER] [-n PORT] [-u USER] [-p PASSWORD]
    omni4d -h | --help
    omni4d --version

Options:
    -l --logging LOGGING       Logging destination (console, file or none) [default: console]
    -v --verbosity VERBOSITY   Logging verbosity [default: info]
    -f --url URL               Url of model file to import
    -d --dbname DBNAME         [default: omni4d]
    -s --server SERVER         Server name or ip address [default: localhost]
    -n --port PORT             Port number for server [default: 2424]
    -u --user USER             DBMS user [default: admin]
    -p --password PASSWORD     DBMS password [default: admin]
    -h --help                  Show a help message
    --version                  Show the version
"""
from docopt import docopt
from omni4d_python.orient import import_model, create_db
from omni4d_python.model import model_from_url
from omni4d_python.session import setup_logging

if __name__ == '__main__':

    arguments = docopt(__doc__, version='Omni4d 0.0.1')

    logging_args = {
        'logging_destination': arguments['--logging'],
        'verbosity': arguments['--verbosity']
    }
    logger = setup_logging(**logging_args)
    logger.debug('arguments: %s' % arguments)

    if arguments['create']:
        command_args = {
            'db_name': arguments['--dbname'],
            'server': arguments['--server'],
            'port': int(arguments['--port']),
            'user': arguments['--user'],
            'password': arguments['--password']
        }
        create_db(**command_args)

    if arguments['import']:
        model = model_from_url(arguments['--url'])
        command_args = {
            'model': model,
            'db_name': arguments['--dbname'],
            'server': arguments['--server'],
            'port': int(arguments['--port']),
            'user': arguments['--user'],
            'password': arguments['--password']
        }
        import_model(**command_args)
