#!/usr/bin/env python
"""Run axelrod
Usage:
    omni4d [-l LOGGING] [-v VERBOSITY] import -f URL [-d DBNAME] [-s SERVER] [-n PORT] [-u USER] [-p PASSWORD]
    omni4d -h | --help
    omni4d --version

Options:
    -l --logging LOGGING       Logging destination (console, file or none) [default: console]
    -v --verbosity VERBOSITY          Logging verbosity [default: info]
    -f --url URL
    -d --dbname DBNAME  [default: omni4d]
    -s --server SERVER  [default: localhost]
    -n --port PORT  [default: 2424]
    -u --user USER  [default: admin]
    -p --password PASSWORD  [default: admin]
    -h --help             Show a help message
    --version             Show the version
"""
from docopt import docopt
from omni4d_python.orient import import_model
from omni4d_python.model import model_from_url
from omni4d_python.session import setup_logging

if __name__ == '__main__':

    arguments = docopt(__doc__, version='Omni4d 0.0.1')
    model = model_from_url(arguments['--url'])
    setup_logging(arguments['--logging'], arguments['--verbosity'])
    import_model(model, arguments['--dbname'], arguments['--server'], int(arguments['--port']), arguments['--user'], arguments['--password'])
